using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DnD_SoloPlayers
{
    public partial class RE_Dungeon : Form
    {
        public RE_Dungeon()
        {
            InitializeComponent();
            this.Icon = Icon.ExtractAssociatedIcon(Application.ExecutablePath);

            List<string> answer = new List<string>();

            //List content

            answer.Add("Under a loose bit of cobblestone on the ground, you see what appears to be a small tunnel. If you reach inside or stick around too long, a living crawling hand jumps out of the hole and attacks. This living hand has been hoarding rings and jewelry in this tunnel.");
            answer.Add("The group finds a long forgotten coin hoard. All is not as it seems, some of the coins are tiny-sized mimics (maybe individuals, maybe swarms), that adhere to and attack those that try to gather the treasure.");
            answer.Add("A crumbling wall with a small tunnel bore through its base hides the resting room for a peaceful Goblin who knows the dungeon well and will give directions or hints in trade for an interesting item.");
            answer.Add("A series of really, staggeringly obvious traps. There’s a tripwire that’s made of thick hemp rope, a wooden pressure plate set in the middle of a cobblestone path, a dark path with a torch set right at the beginning (the torch is crudely attached to a lever on the wall).");
            answer.Add("The ceiling is completely covered with horrid insects – dark, silent and unseen except for the occasional masonry dust they knock loose.");
            answer.Add("Around a corner, you hear clucking. There’s a chicken in the dungeon? You’re three levels down. Shrug: maybe it’s just random. But every three rooms or so, there’s another one, just a chicken walking around and pecking at the dirt. Then you get to a region where there aren’t any chickens. That’s when shit gets real. Because the chickens are a food source.");
            answer.Add("A dead end – The tunnel the party is walking down has them run headlong into a Giant!! Well, the upper torso of the giant. He’s not hostile and is pinned in place by the surrounding walls as he was chasing dinner down a hole and has wiggled himself into this tunnel, blocking any forward movement. If the party attacks him, he will yell and cry, ‘Stop it, please!’ and be overly pathetic, but with his arms pinned at his sides, they will likely kill him in time (suggest higher hit points than normal so the party has to take their time). If they chat with him, he knows a bit about the surrounding rooms as he’s seen creatures moving through the halls and possibly former adventurers. His name is Gordum, and he’s really hungry as he hasn’t eaten in a very long time. Normally, adventurers take pity on him and feed him while they make their way through the dungeon, but the real reason he stays stuck here is a ring of sustenance that he found years ago and pull on ’cause it was shiny.’ If he’s friendly, he offers to watch over the party while they sleep and promises to warn them if anyone else comes down the hallway.");
            answer.Add("A rune trap curses you so that you can’t refuse a request. (Requires the word please to count as a request).");
            answer.Add("A dragon’s cave? – This room is 60 feet (18 Meters) across, and nearly as high, with small pools of water that collect in natural erosions to the west side where an underground stream has formed a small waterfall. The water is chilled and safe, even if it tastes earthy and heavy with minerals. As the group moves into the cave, they likely notice coins littering the edges of the room in small piles and an outcropping halfway up on the east wall… with a snoring, smoking dragon’s head. If the party is quiet, they can sneak through, but any attacks or loud noise wake and do not harm the dragon. It lets out a massive burst of fire over the heads of the group and yells curses as it waves around. Once it finishes, it demands tribute from the group or it will eat them!! In reality, the head and neck are a permanent illusion that was placed in the area to scare off adventurers by a mage who was practicing some new defenses for his study, and a fairy dragon has worked out how to control the illusion and get it to move when he wants. He uses magic to project his voice and sound like a great dragon, and can use a rune placed as part of the illusion to fire a cone of fire 3 times a day that does damage as an ancient dragon. The Fairy Dragon living in a small opening that’s only accessible at the top of the dome ceiling with a meter (2.5 foot) opening that one would need to fly to or us other means. Any tribute that’s left is floated to his home when the adventurers move on and kept there, or discarded around the ground to add to his greatness. (If characters can get to his cave, he should have 2-3 magical items of some note). The little guy has really done well duping people over the years.");
            answer.Add("A dire warning – Moving through this hall, the characters torchlight will cast light through a red ruby the size of an eye that’s been carved to catch and cast the light around the room. If there’s no light, the ruby isn’t found. The light through the ruby displaces words in 5-6 directions saying ‘The Stone of Anolox.’ A group also notices a warning on the wall, one painted with blood and another carved with what must be someone’s finger nails saying – ‘Do not, by any means, touch that gem!’ Anyone who picks up the gem, well, except Anolox, is immediately disintegrated and their ash fills the tunnel.");
            answer.Add("A door painted onto a wall with two door knobs sticking out, one labeled ‘fame’ the other ‘fortune’. Touching fame will turn you as blue as a smurf, only reversible by a wish. Fortune will cause 10,000 cp to fall from the ceiling at great speed causing heavy damage.");
            answer.Add("Bad Directions – A series of alcoves with a skeleton set to perch in each of them. Each is placed alternating up the hallway at 20 ft (6.5 Meter) segments. The first points down the hallway, the next at the floor, and the next straight up, and so on. Every time the party moves past the skeletons, they point a different direction, and it changes every time.");
            answer.Add("Morbid Statuary – A massive room filled with people frozen in time, and in stone. Like creepy stalagmites, hundreds of humanoid statues point up from the ground. One looks like a prince leaning in to kiss a sleeping princess, another is a goblin throwing its hands in the air in panic, and another a cautious knight stalking in his armor. The place looks like a repository for the victims of a gorgon, hopefully long gone.");
            answer.Add("Help us Heroes! – The group comes across an small village that spreads out in a crevace in the wall and stretches for hundreds of feet, but where the ceiling is never more than 4 feet high. This is a village of Myconids that have lived here peacefully ‘since the time of our first spores’ and numbers in the thousands. They beg the party to help them as there is a murdered in the midst. Every day, more and more of their people go missing, and they can’t find the culprit. If they are helped, they will give the party pearls that they collect from nearby shellfish and have saved for years. (The murderer is a kobold with a ring of invisibility and a strange mask to keep from falling to the creatures spores. He REALLY loves cooked mushrooms and has been harvesting the myconids for dinner since finding the village).");
            answer.Add("Welcome Matt – The group comes to a door rigged with a number of traps. A line at the top that pulls something above the door if it’s opened, a pressure plate that’s released from the bottom if the door is opened, poison darts that fire from the wall behind it, the works! All the traps are fairly easy to spot and disarm, and there are 6 total. An exceeding high perception check is needed to hear that there’s a small click after each trap is set off or disarmed. Once all six have been triggered, the real trap occurs. The walls 30 feet to either side of the door slam into the ceiling (these are 10ft cubes). At the same time, the floor drops out under the door at a steep angle to a smooth shoot, and the walls start moving in. While it looked like there was something behind the door, it leads no where but a series of mirrors that look like a nearly endless hallway, and with the walls closing in, the only way is down. Those characters that do slide down are eventually deposited into a large cage where a robed figure covered in bandages whips around and screams, ‘Happy Birthday Matt!’ He’s then disappointed that you and yours are not Matt. After muttering to himself for a while, he eventually apologizes for the ‘trap’ and releases the group, showing them to a set of stairs that head back to the tunnel. They don’t run into this encounter again.");
            answer.Add("Poor soul- you find a skeleton chained to the wall. When you approach, you realize it is an undead. He is scared when you approach and explains that he was trapped here and was brought back from death to continue his torment. Who put him there is up to the dm. Also whether or not he is lying is up to you.");
            answer.Add("The room nullifies any sounds made, players must communicate entirely through gestures OOC.");
            answer.Add("The door opens up into a mirror dimension flipped horizontally, any and all actions taken are performed by the doubles on the other side, including stepping through the doorway. If a PC attempts to talk they are interrupted by themselves.");
            answer.Add("The party walks down a hallway which and comes across an opening on one side leading into a large open room. Stepping on a trap in the middle of the open room causes the door to shut and the ceiling to begin to collapse – but only as long as one member of the party is still in the first hallway. That party member can disarm the trap, opening the door and raising the ceiling by finding a recess on the wall in the hallway with a switch in it. If they fail a roll on the first attempt they only manage to stick their hand through a hole into the room and have to search for a second recess.");
            answer.Add("A large pit, filled at the bottom with spikes and scorpions. A sign is just visible on one side of the pit. A successful perception check, or a party member being dangled by their feet, can detect that the sign is upside down and says ‘LEARN THE WORDS’.");
            answer.Add("The skeletal remains of a man can also bee seen at the bottom of the pit, still wearing black pants, suspenders, a shirt with horizontal black and white stripes, white gloves, and with a black beret perched atop its bleached skull.");
            answer.Add("A gnome sorcerer with short term memory has been trying to find this dungeons hoard for the last 10 years, but keeps forgetting which way he came from.");
            answer.Add("A large banquet hall, with pewter utensils, earthenware plates, and fine food. The walls are draped in common but warm furs, and the table is lit with some nice candelabras (2gp each). There are 2x(Party Size) seats at the table, and at the head is a stout, ruddy faced bearded earl who warmly beckons to the party. ‘Welcome,’ he he says, voice booming, ‘our other guests are almost here. Please, sit down.’ Seat the most interesting mix of NPCs, Villains, and historical figures at the table. The banquet quests are compelled to not make any hostile action in the room. The non-party guests are returned to whatever place and time they were in before the meal.");
            answer.Add("A merchant adventurer (CR party level+1, true neutral alignment) has set up a table, chairs, and all manner of interesting equipment to sell to whomever happens to wander by.");
            answer.Add("A wandering mycologist is looking for the weirdest mushrooms that you can find for their latest thesis/monograph. Not only will he pay (not much) for any mushrooms you can help him find, but you’ll get a mention in his paper! Think of the exposure! All the biggest mycologists in the region will be talking about this.");
            answer.Add("In a this room, there is a dividing wall with a doorway. On this dividing wall are a series of colorful masks. Around the dividing wall appears to be a large wooden table with 10 chairs, 8 of them already filled with large creatures (a mix of monsters and/or adventurers in any combination) playing Texas hold’em poker for coin and valuables. No one is talking. Any players at the table who notice you will stop, stare, and point silently to the masks. Any two party members who wear the masks can join the game.");
            answer.Add("The party walks in on a group of hostile hobgoblins in the middle of them practicing their synchronized dance routine. After one round of surprised embarrassment, they will attack unless the players either start playing music or challenge them to a dance off.");
            answer.Add("This room contains a hole with a wooden bucket on a string suspended over a large, clear pool of water. The bucket hangs down through a circular hole in the ceiling, leading up to a well. As the player’s approach, a coin falls down the hole, and a distant voice calls: ‘Magical well, I seek thy wisdom!’.");
            answer.Add("This room is round, with a concave floor. Three large, metal spinning tops whirl magically around and around, bashing into each other seemingly at random. On a balcony wrapping around the room are three goblin shamans, engaging in their favorite pastime, BattleTop. Each controls the tops with a small, delicate handheld contraption. The tops will cease spinning if the contraption is broken, or if they leave the room for more than 1d4 days.");
            answer.Add("This area of the dungeon appears to be under construction. Goblin work crews and ogre haulers are lead by hobgoblin foremen, building out new rooms and defenses according to blueprints lying unprotected on a table off to the side momentarily forgotten.");
            answer.Add("Three nothics sit, pouring over old tomes and scrolls, lit by blue crystals scattered on a pedestal. On the wall, a giant, engraved flaming eye is engraved. Staring at the carving of the eye for any significant length of time (DM’s discretion, but at least a few minutes) grants advantage on wisdom checks until the player’s next long rest. The player feels compelled to be unable to rest for the next two days, and is exhausted on the third day.");
            answer.Add("Carved on the wall in code are the letters…H-A-S-T-U-R. If deciphered and spoken aloud, then whosoever speaks the name of this horrid Elder God, HIM WHO IS NOT TO BE NAMED must make a saving throw against magic or a Byhakhee will be gated in and attack (or the PC may go insane?).");
            answer.Add("You walk into the next chamber and find a stone statue of a man reaching for a gold ring on a pedestal. The ring, when worn for at least 1 day, gives you +1 to all saving throws for each day it has been worn for up to a week, but if you take it off you suffer the inverse of that bonus for as long as you had it on. You can’t sell the ring. Putting the ring on the man’s finger will restore him from stone, at which point he reveals this ring was the result of a transmutation spell going horribly wrong. He gives you a level appropriate large sum of gold for releasing him and goes off on his merry way.");
            answer.Add("The ceiling of the dungeon tunnel has partially collapsed down, making it very difficult to get past. Characters would have to strip off any medium or heavier armor and backpacks to crawl past it. Investigating it more reveals some furniture at the top of the rubble near the ceiling, indicating a room above, but investigating it will probably complete the collapse and prevent further exploration down the tunnel.");
            answer.Add("A several story deep library attended to by a seemingly human librarian that doesn’t know his library is deep in an underground dungeon. The stacks are littered with skeletons of all shapes and sizes but it doesn’t seem to bother the attendant. Now that you mention it, it has been a few years since he’s had anyone visit. That is, of course, anyone besides the necromancer that comes by every so often. – defeating the necromancer and his skeletons allows you access to the library. It contains a bunch of spell books for the wizards in your party, some defensive magical items, a moderate stash of gold, and a heap of baubles and nearly insignificant magical items.");
            answer.Add("An undead, but coherrent, merchant runs a small item shop in the depths of the dungeon. The shopkeep is a little mad, but seems content to run a shop with average or slightly below average prices on basic goods (maybe a few rarities at DM’s discretion.) The Merchant seems disinterested in the world beyond the room their shop is located in, and if pressed seems to think they’re getting new supplies in once a week. Will react accordingly if the PCs attempt to cheat or steal from them.");
            answer.Add("An archway has been heavily barricaded and the area around it has sign postings in the language of the dungeon’s inhabitants with stern warning to stay away. Skittering can be heard from within. Inside is a wing of the dungeon containing a burrow having broken through the wall and an infestation of subterranean creatures of the DM’s choice. (Possibly of a high CR to make this optional wing and its loot a real challenge to the PCs)");
            answer.Add("A patch of wall indiscernible from the rest of the dungeon except for the incredibly soft quality of the stone. A small alcove containing a slightly inhuman skeleton is on the other side.");
            answer.Add("A room that has no gravity.");
            answer.Add("A crack in the floor that constantly streams out a thin wisp of smoke. It smells of honey.");
            answer.Add("A docile monster that is permanently invisible.");
            answer.Add("A room with a large central pool in which an elemental lives, protecting a powerful artifact.");
            answer.Add("The ghost of an adventurer that became lost in the dungeon years ago.");
            answer.Add("Foolish forebears- Ghosts of an adventuring party that died there long ago. They re-enact the the moments leading up to their deaths with no notice of the players. They can help lead them through the dungeon, and even offer information the players don’t know. Eventually though they will lead the party into a trap or deadly encounter");
            answer.Add("Nuka skeletons- A room with the charred skeletons of dead adventurers. The walls are burnt black with the only thing juxtaposing it being the perfect white silhouettes of their final moments. When the player’s backs are turned the silhouettes move, and begin attacking the players. The skeletons get up, and their burnt black bones come alive with fiery cracks not dissimilar to embers left in the bottom of a bonfire.");
            answer.Add("Murder mystery spectacular-A doorway that leads into a well set dining room has an instant kill trap thst extracts people’s souls from their bodies. They now have to act as ghosts in a murder mystery dinner party, and can get back in their bodies once they have helped solve the mystery. They are unable to communicate with anyone directly, but they can ‘haunt’ things to send messages.");
            answer.Add("Arachnid ally-A spider living in an old shoe offers information to adventurers for a modest fee. She can offer shortcuts, intel, and hidden passages");
            answer.Add("Pilfering party-Another adventuring party has been stealthily following the party, and plan to jump them in the treasure room.");
            answer.Add("No blinking!- As soon as the players step into this room the door locks behind them. The room is mostly normal with the exception that one wall has the words ‘no blinking!’ Written out in huge letters. If the players blink they see where the key is hidden, but only for a split second.");
            answer.Add("A room filled with artifacts such as gems, ancient pots, weapons. Some are on pedestals but most are scattered on the floor as if someone has ransacked it but left everything inside. A small, golden statue of a dragon lies smashed by an empty pedestal, and at the end is a locked door with no keyhole. A large mirror leans against the wall on the left of the path. Reflected in it is the room, but with everything carefully arranged and the dragon statue unbroken on the pedestal. If the players attempt to steal anything, the pathway they came through liquidates and melts, across, trapping anyone inside the room and crushing anyone in the hall, until it is placed back where it was found. If the room is arranged like in the mirror, including mending the dragon statue, the door at the end slides open.");
            answer.Add("A hole in the wall, about the height of human shoulders. There is something shiny on the deep end of the hole, however to reach that, you would have to reach inside, and it’s deep enough to swallow your arm up he shoulder. If you reach inside, something bites you, causing 1d4 piercing damage. If you reach inside again, nothing bites you and you are free to take the shiny thing. It’s a single goldpiece.");
            answer.Add("An old gnome is sat on a barrel smoking a pipe in a corridor of the dungeon, where the path splits into two. He gives the players a pleasant smile, and starts chatting about the draught. If they ask about how he came to be there at gives a vague answer about knocking the area well and directs them down left corridor, promising it’s worth their while. If they do they find a backpack filled with old treasure worth 30gp and the skeleton of a gnome lying beside it. If they go back, the old gnome is gone without a trace.");
            answer.Add("A large disk floats rotating, a few inches from the circular walls of the room. Through the cracks you can see a deep chasm. At even spaces around the walls there are open and empty tombs, each with a seal floating above it. If the players all venture into the disk it will activate and spin violently, using its centrifugal force to push the players into the tombs or the entrance or exit.");
            answer.Add("The ghost of the now crumbling manor is not pleased that some adventures are taking his stuff, but instead of attacking, he tries to find some middle ground with the group so he can be left in peace.");
            answer.Add("In front of the party is a large stone door, possibly of gnomish construction that is covered in thin grooves that seem to make out a labyrinthine maze. In the middle is large ruby red gem that, when touched, shrinks the party and puts them somewhere random inside of it. In order to re-enlarge themselves and exit the labyrinth (thus opening the door) they must find their way back to the gem that now looms menacingly overhead while dodging mechanical spiders and tiny traps.");
            answer.Add("A tiny telepathic spider offers to show them to a secret shortcut to the end of the dungeon. When followed a phase spider ambushes the party and thanks its child for bringing home dinner");
            //56 answers

            //End list content

            //random to select answer from list
            Random rnd = new Random();

            int select = rnd.Next(0, answer.Count);

            textBox1.Text = (answer[select].ToString());
        }
    }
}
